debug

diff --git a/ansible/roles/zfs-backup-server/templates/pull-zfs-backups.sh.j2 b/ansible/roles/zfs-backup-server/templates/pull-zfs-backups.sh.j2
--- a/ansible/roles/zfs-backup-server/templates/pull-zfs-backups.sh.j2
+++ b/ansible/roles/zfs-backup-server/templates/pull-zfs-backups.sh.j2
@@ -200,20 +200,23 @@ then
 SYNCOID_COMMAND="sudo /usr/sbin/syncoid --no-privilege-elevation --no-sync-snap --quiet --recursive {{ vault_zfsbackups_user }}@{{ zfsbackup_client }}$SEARCHDOMAIN:{{zfs_backup_dataset}} {{ zfsbackup_poolname }}/{{ zfsbackup_client }}/{{zfs_backup_dataset}}"
 SYNCOID_OUTPUT=$( $SYNCOID_COMMAND 2>&1 )
 
+if [ $? -eq 0 ]
+then
+		log_info "{{zfs_backup_dataset}}..."
+		log_info "Success!"
+else
+		FAILURE=1
+		log_info "{{zfs_backup_dataset}}..."
+		log_error "Failure!" 
+		log_error $SYNCOID_OUTPUT
+fi
+
 if [[ "$LOGLEVEL" =~ ^(DEBUG)$ ]]; then
 echo $SYNCOID_COMMAND
 echo $SYNCOID_OUTPUT
 fi
 
-log_info "{{zfs_backup_dataset}}..."
-if [ $? -eq 0 ]
-then
-		log_info "Success!"
-else
-		FAILURE=1
-		log_error "Failure!" 
-		log_error $SYNCOID_OUTPUT
-fi
+
 {% endfor %} # End dataset loop
 
 log_info "{{ zfsbackup_client }} backup finished."
