Tidy up zfs-backup script

diff --git a/ansible/roles/zfs-backup-server/templates/zfs-backup.sh.j2 b/ansible/roles/zfs-backup-server/templates/zfs-backup.sh.j2
--- a/ansible/roles/zfs-backup-server/templates/zfs-backup.sh.j2
+++ b/ansible/roles/zfs-backup-server/templates/zfs-backup.sh.j2
@@ -8,6 +8,43 @@ ERROR_FILE=zfsbackup_logging_errorfile
 BACKUP_ADDRESS={{zfsbackup_target_server}}
 FAILURE=0
 
+sleepnow() {
+	# Sleep if script is present
+	command -v sleepuntil.sh
+	if [ $? -eq 0 ]; 
+	then 
+		echo "Going to sleep in 5 mins. Will wake up at {{ sleepuntil_sleep_time }}."
+		sleep 300
+		sleepuntil.sh "{{ sleepuntil_sleep_time }}"
+	fi 
+}
+
+success () {
+	echo "Backup success"
+	{% if zfsbackup_healthcheck_send %}
+	curl -fsSL https://hc-ping.com/{{ vault_autorestic_ping_key }}/host-backups-daily-zfs-backup-pull
+	{% endif %}
+	{% if zfsbackup_beep %}
+	env -u SUDO_GID -u SUDO_COMMAND -u SUDO_USER -u SUDO_UID beep -f 130 -l 100 -n -f 262 -l 100 -n -f 330 -l 100 -n -f 392 -l 100 -n -f 523 -l 100 -n -f 660 -l 100 -n -f 784 -l 300 -n -f 660 -l 300 -n -f 146 -l 100 -n -f 262 -l 100 -n -f 311 -l 100 -n -f 415 -l 100 -n -f 523 -l 100 -n -f 622 -l 100 -n -f 831 -l 300 -n -f 622 -l 300 -n -f 155 -l 100 -n -f 294 -l 100 -n -f 349 -l 100 -n -f 466 -l 100 -n -f 588 -l 100 -n -f 699 -l 100 -n -f 933 -l 300 -n -f 933 -l 100 -n -f 933 -l 100 -n -f 933 -l 100 -n -f 1047 -l 400
+	{% endif %}
+	echo "\n"
+
+	sleepnow
+}
+
+failure () {
+    echo "Backup failure - logged to $LOGGING_DIR/$ERROR_FILE"
+	{% if zfsbackup_beep %}
+    env -u SUDO_GID -u SUDO_COMMAND -u SUDO_USER -u SUDO_UID beep -f 5000 -l 50 -r 6
+	{% endif %}
+	{% if zfsbackup_pushover %}
+    /usr/bin/curl -s --form-string token="{{vault_pushover_home_automation_key}}" --form-string user="{{vault_pushover_user_key}}" --form-string message="Backup failed - $(date --iso-8601=seconds)" https://api.pushover.net/1/messages.json
+	{% endif %}
+	echo ""
+	sleepnow
+}
+
+
 mkdir -p $LOGGING_DIR
 touch $LOGGING_DIR/$LOGGING_FILE
 
@@ -23,6 +60,7 @@ then
   echo $BACKUP_ADDRESS online. Proceeding.
 else 
   echo $BACKUP_ADDRESS offline. Failure.
+  failure
   exit 1 
 fi 
 
@@ -55,30 +93,8 @@ echo " " >> $LOGGING_DIR/$LOGGING_FILE
 # Notify of outcome
 if [ $FAILURE -eq 1 ]
 then
-    echo "Backup failure - logged to $LOGGING_DIR/$ERROR_FILE"
-	{% if zfsbackup_beep %}
-    env -u SUDO_GID -u SUDO_COMMAND -u SUDO_USER -u SUDO_UID beep -f 5000 -l 50 -r 6
-	{% endif %}
-	{% if zfsbackup_pushover %}
-    /usr/bin/curl -s --form-string token="{{vault_pushover_home_automation_key}}" --form-string user="{{vault_pushover_user_key}}" --form-string message="Backup failed - $(date --iso-8601=seconds)" https://api.pushover.net/1/messages.json
-	{% endif %}
-	echo "\n"
+	failure
 else
-    echo "Backup success"
-    echo "Going to sleep..."
-	{% if zfsbackup_healthcheck_send %}
-	curl -fsSL https://hc-ping.com/{{ vault_autorestic_ping_key }}/host-backups-daily-zfs-backup-pull
-	{% endif %}
-	{% if zfsbackup_beep %}
-	env -u SUDO_GID -u SUDO_COMMAND -u SUDO_USER -u SUDO_UID beep -f 130 -l 100 -n -f 262 -l 100 -n -f 330 -l 100 -n -f 392 -l 100 -n -f 523 -l 100 -n -f 660 -l 100 -n -f 784 -l 300 -n -f 660 -l 300 -n -f 146 -l 100 -n -f 262 -l 100 -n -f 311 -l 100 -n -f 415 -l 100 -n -f 523 -l 100 -n -f 622 -l 100 -n -f 831 -l 300 -n -f 622 -l 300 -n -f 155 -l 100 -n -f 294 -l 100 -n -f 349 -l 100 -n -f 466 -l 100 -n -f 588 -l 100 -n -f 699 -l 100 -n -f 933 -l 300 -n -f 933 -l 100 -n -f 933 -l 100 -n -f 933 -l 100 -n -f 1047 -l 400
-	{% endif %}
-	echo "\n"
-
-	# Sleep if script is present
-	command -v sleepuntil.sh
-	if [ $? -eq 0 ]; 
-	then 
-		sleep 300
-		sleepuntil.sh "{{ sleepuntil_sleep_time }}"
-	fi 
+	success
 fi
+
