debug

diff --git a/ansible/roles/zfs-backup-server/templates/zfs-backup.sh.j2 b/ansible/roles/zfs-backup-server/templates/zfs-backup.sh.j2
--- a/ansible/roles/zfs-backup-server/templates/zfs-backup.sh.j2
+++ b/ansible/roles/zfs-backup-server/templates/zfs-backup.sh.j2
@@ -24,40 +24,40 @@ echo "Search domain: $SEARCHDOMAIN"
 echo " "
 
 sleepnow() {
-	# Sleep if script is present
-	command -v sleepuntil.sh
-	if [ $? -eq 0 ]; 
-	then 
-		echo "Going to sleep in 5 mins. {{ ansible_hostname }} will wake up at {{ sleepuntil_sleep_time }}."
-		secs=$((5 * 60))
-		while [ $secs -gt 0 ]; do
-			echo -ne "$secs\033[0K\r"
-			sleep 1
-			: $((secs--))
-		done
-		echo "Sleeping..."
-		sleepuntil.sh "{{ sleepuntil_sleep_time }}"
-	fi 
+    # Sleep if script is present
+    command -v sleepuntil.sh
+    if [ $? -eq 0 ]; 
+    then 
+        echo "Going to sleep in 5 mins. {{ ansible_hostname }} will wake up at {{ sleepuntil_sleep_time }}."
+        secs=$((5 * 60))
+        while [ $secs -gt 0 ]; do
+            echo -ne "$secs\033[0K\r"
+            sleep 1
+            : $((secs--))
+        done
+        echo "Sleeping..."
+        sleepuntil.sh "{{ sleepuntil_sleep_time }}"
+    fi 
 }
 
 success () {
-	echo "Backup success"
-	{% if zfsbackup_healthcheck_send %}
-	curl -fsSL https://hc-ping.com/{{ vault_autorestic_ping_key }}/host-backups-daily-zfs-backup-pull
-	{% endif %}
-	echo ""
+    echo "Backup success"
+    {% if zfsbackup_healthcheck_send %}
+    curl -fsSL https://hc-ping.com/{{ vault_autorestic_ping_key }}/host-backups-daily-zfs-backup-pull
+    {% endif %}
+    echo ""
 
-	sleepnow
+    sleepnow
 }
 
 failure () {
     echo "Backup failure - logged to $LOGGING_DIR/$ERROR_FILE"
-	{% if zfsbackup_pushover %}
+    {% if zfsbackup_pushover %}
     /usr/bin/curl -s --form-string token="{{vault_pushover_home_automation_key}}" --form-string user="{{vault_pushover_user_key}}" --form-string message="Backup failed - $(date --iso-8601=seconds)" https://api.pushover.net/1/messages.json
-	{% endif %}
-	echo ""
+    {% endif %}
+    echo ""
 
-	sleepnow
+    sleepnow
 }
 
 
@@ -93,40 +93,40 @@ else
   failure
 
 
-echo "[$(date --iso-8601=seconds)] Started {{ zfsbackup_client }} backup run" >> $LOGGING_DIR/$LOGGING_FILE
+  echo "[$(date --iso-8601=seconds)] Started {{ zfsbackup_client }} backup run" >> $LOGGING_DIR/$LOGGING_FILE
 
-# Backup these datasets: {{hostvars[zfsbackup_client]['zfs_backup_datasets']}}
+  # Backup these datasets: {{hostvars[zfsbackup_client]['zfs_backup_datasets']}}
 
-{% for zfs_backup_dataset in hostvars[zfsbackup_client]['zfs_backup_datasets'] %}
+  {% for zfs_backup_dataset in hostvars[zfsbackup_client]['zfs_backup_datasets'] %}
 
-echo Backup {{ zfsbackup_client }}:{{ zfs_backup_dataset }}
-echo "[$(date --iso-8601=seconds)] START {{zfs_backup_dataset}} "
+  echo Backup {{ zfsbackup_client }}:{{ zfs_backup_dataset }}
+  echo "[$(date --iso-8601=seconds)] START {{zfs_backup_dataset}} "
 
-echo "[$(date --iso-8601=seconds)] START {{zfs_backup_dataset}} " >> $LOGGING_DIR/$LOGGING_FILE
-SYNCOID_OUTPUT=$( /usr/sbin/syncoid --sendoptions=Rw --no-privilege-elevation --no-sync-snap --quiet {{ zfs_backup_user }}@{{ zfsbackup_client }}.$SEARCHDOMAIN:{{zfs_backup_dataset}} backuppool/{{ zfsbackup_client }}/{{zfs_backup_dataset}} 2>&1 )
+  echo "[$(date --iso-8601=seconds)] START {{zfs_backup_dataset}} " >> $LOGGING_DIR/$LOGGING_FILE
+  SYNCOID_OUTPUT=$( /usr/sbin/syncoid --sendoptions=Rw --no-privilege-elevation --no-sync-snap --quiet {{ zfs_backup_user }}@{{ zfsbackup_client }}.$SEARCHDOMAIN:{{zfs_backup_dataset}} backuppool/{{ zfsbackup_client }}/{{zfs_backup_dataset}} 2>&1 )
 
-echo $SYNCOID_OUTPUT
+  echo $SYNCOID_OUTPUT
 
-if [ $? -eq 0 ]
-then
-    echo "[$(date --iso-8601=seconds)] SUCCESS {{zfs_backup_dataset}}" >> $LOGGING_DIR/$LOGGING_FILE
-		echo "Successfully backed up {{zfs_backup_dataset}}"
-else
-    FAILURE=1
-    echo "[$(date --iso-8601=seconds)] FAILURE {{zfs_backup_dataset}} " >> $LOGGING_DIR/$LOGGING_FILE
-    echo "[$(date --iso-8601=seconds)] FAILURE {{zfs_backup_dataset}} " >> $LOGGING_DIR/$ERROR_FILE
-    echo "[$(date --iso-8601=seconds)] FAILURE OUTPUT: " >> $LOGGING_DIR/$ERROR_FILE
-    echo $SYNCOID_OUTPUT >> $LOGGING_DIR/$ERROR_FILE
-	echo $SYNCOID_OUTPUT
-fi
-echo "[$(date --iso-8601=seconds)] END {{zfs_backup_dataset}} " >> $LOGGING_DIR/$LOGGING_FILE
-echo "[$(date --iso-8601=seconds)] END {{zfs_backup_dataset}} "
-{% endfor %}
+  if [ $? -eq 0 ]
+  then
+      echo "[$(date --iso-8601=seconds)] SUCCESS {{zfs_backup_dataset}}" >> $LOGGING_DIR/$LOGGING_FILE
+          echo "Successfully backed up {{zfs_backup_dataset}}"
+  else
+      FAILURE=1
+      echo "[$(date --iso-8601=seconds)] FAILURE {{zfs_backup_dataset}} " >> $LOGGING_DIR/$LOGGING_FILE
+      echo "[$(date --iso-8601=seconds)] FAILURE {{zfs_backup_dataset}} " >> $LOGGING_DIR/$ERROR_FILE
+      echo "[$(date --iso-8601=seconds)] FAILURE OUTPUT: " >> $LOGGING_DIR/$ERROR_FILE
+      echo $SYNCOID_OUTPUT >> $LOGGING_DIR/$ERROR_FILE
+      echo $SYNCOID_OUTPUT
+  fi
+  echo "[$(date --iso-8601=seconds)] END {{zfs_backup_dataset}} " >> $LOGGING_DIR/$LOGGING_FILE
+  echo "[$(date --iso-8601=seconds)] END {{zfs_backup_dataset}} "
+  {% endfor %}
 
-echo "[$(date --iso-8601=seconds)] Finished backup run" >> $LOGGING_DIR/$LOGGING_FILE
-echo " " >> $LOGGING_DIR/$LOGGING_FILE
-echo "---------------------" >> $LOGGING_DIR/$LOGGING_FILE
-echo " " >> $LOGGING_DIR/$LOGGING_FILE
+  echo "[$(date --iso-8601=seconds)] Finished backup run" >> $LOGGING_DIR/$LOGGING_FILE
+  echo " " >> $LOGGING_DIR/$LOGGING_FILE
+  echo "---------------------" >> $LOGGING_DIR/$LOGGING_FILE
+  echo " " >> $LOGGING_DIR/$LOGGING_FILE
 
 fi # End online check
 # ------------------------------------------------
@@ -142,8 +142,8 @@ echo " "
 # Notify of outcome
 if [ $FAILURE -eq 1 ]
 then
-	failure
+    failure
 else
-	success
+    success
 fi
 
