clean up backup script

diff --git a/ansible/roles/zfs-backup-server/templates/zfs-backup.sh.j2 b/ansible/roles/zfs-backup-server/templates/zfs-backup.sh.j2
--- a/ansible/roles/zfs-backup-server/templates/zfs-backup.sh.j2
+++ b/ansible/roles/zfs-backup-server/templates/zfs-backup.sh.j2
@@ -1,5 +1,91 @@
 #!/usr/bin/env bash
 
+
+#################################
+# Constants / global variables
+#################################
+LOGFILE='example.log'
+LOGLEVEL='INFO'
+QUIET=0 # verbose by default
+
+LOGDIR={{zfsbackup_logging_dir}}
+LOGFILE={{zfsbackup_logging_successfile}}
+FAILURE=0 # default is success
+SEARCHDOMAIN=.i.affordablepotatoes.com
+#################################
+# Functions
+#################################
+
+# Logging functions
+function log_output {
+  if [ $QUIET -eq 1 ] then
+    echo `date "+%Y/%m/%d %H:%M:%S"`" $1"
+  fi
+  echo `date "+%Y/%m/%d %H:%M:%S"`" $1" >> $LOGDIR/$LOGFILE
+}
+
+function log_debug {
+  if [[ "$LOGLEVEL" =~ ^(DEBUG)$ ]]; then
+    log_output "DEBUG $1"
+  fi
+}
+
+function log_info {
+  if [[ "$LOGLEVEL" =~ ^(DEBUG|INFO)$ ]]; then
+    log_output "INFO $1"
+  fi
+}
+
+function log_warn {
+  if [[ "$LOGLEVEL" =~ ^(DEBUG|INFO|WARN)$ ]]; then
+    log_output "WARN $1"
+  fi
+}
+
+function log_error {
+  if [[ "$LOGLEVEL" =~ ^(DEBUG|INFO|WARN|ERROR)$ ]]; then
+    log_output "ERROR $1"
+  fi
+}
+
+# Some other helper functions
+# ...
+
+# Help output
+function usage {
+  echo
+  echo "This is a Bash script template"
+  echo "Usage: ./zfs-backup -l <logfile> -L <loglevel> --quiet"
+  echo "Example: ./zfs-backup -l example.log -L INFO --quiet"
+  echo
+}
+
+#################################
+# Main
+#################################
+
+# Get input parameters
+while [[ "$1" != "" ]]; do
+  case $1 in
+      -l | --logfile )        shift
+                              LOGFILE=$1
+                              ;;
+      -L | --loglevel )       shift
+                              LOGLEVEL=$1
+                              ;;
+      -Q | --quiet )          shift
+                              QUIET=1
+                              ;;
+      -h | --help )           usage
+                              exit
+                              ;;
+      * )                     usage
+                              exit 1
+  esac
+  shift
+done
+
+
 echo "ZFS Backups"
 echo "***********"
 echo " "
@@ -14,16 +100,10 @@ while [ $pausesecs -gt 0 ]; do
 done
 echo " "
 
-LOGGING_DIR={{zfsbackup_logging_dir}}
-LOGGING_FILE={{zfsbackup_logging_successfile}}
-ERROR_FILE={{zfsbackup_logging_errorfile}}
-FAILURE=0
-SEARCHDOMAIN=.i.affordablepotatoes.com
 
 echo "DEBUG INFO"
 echo "***********"
-echo "Logging to: $LOGGING_DIR/$LOGGING_FILE"
-echo "Logging errors to: $LOGGING_DIR/$ERROR_FILE"
+echo "Logging to: $LOGDIR/$LOGFILE"
 echo "Search domain: $SEARCHDOMAIN"
 echo " "
 
@@ -45,28 +125,24 @@ sleepnow() {
 }
 
 success () {
-    echo "✅ [$(date --iso-8601=seconds)] Backup success"
+    log_info "✅ Backup success!"
     {% if zfsbackup_healthcheck_send %}
     curl -fsSL https://hc-ping.com/{{ vault_autorestic_ping_key }}/host-backups-daily-zfs-backup-pull
     {% endif %}
-    echo ""
-
     sleepnow
 }
 
 failure () {
-    echo "🛑 [$(date --iso-8601=seconds)] Backup failure - logged to $LOGGING_DIR/$ERROR_FILE"
+    log_error "❌ Backup failure."
     {% if zfsbackup_pushover %}
     /usr/bin/curl -s --form-string token="{{vault_pushover_home_automation_key}}" --form-string user="{{vault_pushover_user_key}}" --form-string message="Backup failed - $(date --iso-8601=seconds)" https://api.pushover.net/1/messages.json
     {% endif %}
-    echo ""
-
     sleepnow
 }
 
 
-mkdir -p $LOGGING_DIR
-touch $LOGGING_DIR/$LOGGING_FILE
+mkdir -p $LOGDIR
+touch $LOGDIR/$LOGFILE
 
 # Perform Ansible pull while the machine is awake
 {% if (zfsbackup_ansiblepull_workdir) and (zfsbackup_ansiblepull_script_name) %}
@@ -82,21 +158,19 @@ echo "Backing up {{ zfsbackup_client }}."
 echo "**********************************"
 
 ## Is the backup host up?
-echo "💭 [$(date --iso-8601=seconds)] Pinging {{ zfsbackup_client }}$SEARCHDOMAIN"
+log_info "Pinging {{ zfsbackup_client }}$SEARCHDOMAIN"
 ping "{{ zfsbackup_client }}$SEARCHDOMAIN" -c2 > /dev/null 2>&1
 
 if [ $? -eq 0 ]; 
 then 
-  echo "✅ [$(date --iso-8601=seconds)] {{ zfsbackup_client }} online. Proceeding."
+  log_info "{{ zfsbackup_client }} online. Proceeding."
 
-  echo "[$(date --iso-8601=seconds)] Started {{ zfsbackup_client }} backup run" >> $LOGGING_DIR/$LOGGING_FILE
+  log_info "[Started {{ zfsbackup_client }} backup run."
 
   # Backup these datasets: {{hostvars[zfsbackup_client]['zfs_backup_datasets']}}
 
   {% for zfs_backup_dataset in hostvars[zfsbackup_client]['zfs_backup_datasets'] %}
-
-  echo "💭 [$(date --iso-8601=seconds)] Start backup of {{ zfsbackup_client }}:{{ zfs_backup_dataset }}"
-  echo "[$(date --iso-8601=seconds)] START {{zfs_backup_dataset}} " >> $LOGGING_DIR/$LOGGING_FILE
+  log_info "START {{zfs_backup_dataset}}"
   SYNCOID_COMMAND="/usr/sbin/syncoid --sendoptions=Rw --no-privilege-elevation --no-sync-snap --quiet {{ vault_zfsbackups_user }}@{{ zfsbackup_client }}$SEARCHDOMAIN:{{zfs_backup_dataset}} backuppool/{{ zfsbackup_client }}/{{zfs_backup_dataset}}"
 
   #echo "💭 -----------------------"
@@ -107,30 +181,18 @@ then
 
   if [ $? -eq 0 ]
   then
-      echo "[$(date --iso-8601=seconds)] SUCCESS {{zfs_backup_dataset}}" >> $LOGGING_DIR/$LOGGING_FILE
-      echo "✅ [$(date --iso-8601=seconds)] Successfully backed up {{zfs_backup_dataset}}"
+      log_info "SUCCESS {{zfs_backup_dataset}}"
   else
       FAILURE=1
-      echo "[$(date --iso-8601=seconds)] FAILURE {{zfs_backup_dataset}} " >> $LOGGING_DIR/$LOGGING_FILE
-      echo "[$(date --iso-8601=seconds)] FAILURE {{zfs_backup_dataset}} " >> $LOGGING_DIR/$ERROR_FILE
-      echo "[$(date --iso-8601=seconds)] FAILURE OUTPUT: " >> $LOGGING_DIR/$ERROR_FILE
-      echo $SYNCOID_OUTPUT >> $LOGGING_DIR/$ERROR_FILE
-
-      echo "🛑 [$(date --iso-8601=seconds)] Syncoid failure backing up {{zfs_backup_dataset}}"
-      # echo "💭 [$(date --iso-8601=seconds)] MSG: $SYNCOID_OUTPUT"
+      log_error "FAILURE {{zfs_backup_dataset}}" 
+      log_error $SYNCOID_OUTPUT
   fi
-  echo "[$(date --iso-8601=seconds)] END {{zfs_backup_dataset}} " >> $LOGGING_DIR/$LOGGING_FILE
-  echo "💭 [$(date --iso-8601=seconds)] END {{zfs_backup_dataset}}"
-  echo " "
+  log_info "END {{zfs_backup_dataset}} "
   {% endfor %}
 
-  echo "[$(date --iso-8601=seconds)] Finished backup run" >> $LOGGING_DIR/$LOGGING_FILE
-  echo " " >> $LOGGING_DIR/$LOGGING_FILE
-  echo "---------------------" >> $LOGGING_DIR/$LOGGING_FILE
-  echo " " >> $LOGGING_DIR/$LOGGING_FILE
+  log_info "Finished backup run."
 else 
-  echo "🛑 [$(date --iso-8601=seconds)] {{ zfsbackup_client }} offline. Failure."
-  echo " "
+  log_error "{{ zfsbackup_client }} was not online."
   failure
 fi # End online check
 # ------------------------------------------------
