WIP

diff --git a/ansible/roles/zfs-tools-backup-server/templates/backup.sh.j2 b/ansible/roles/zfs-tools-backup-server/templates/backup.sh.j2
--- a/ansible/roles/zfs-tools-backup-server/templates/backup.sh.j2
+++ b/ansible/roles/zfs-tools-backup-server/templates/backup.sh.j2
@@ -2,17 +2,20 @@
 
 sleep 60
 
-BACKUP_DIR=/var/log/backups/
-BACKUP_FILE=backups.log
-BACKUP_FILE_FAILURE=error.log
+LOGGING_DIR=/var/log/backups
+LOGGING_FILE=backups.log
+ERROR_FILE=error.log
+# BACKUP_ADDRESS=10.8.0.116
 BACKUP_ADDRESS=192.168.1.116
 FAILURE=0
 
-mkdir -p $BACKUP_DIR
-touch $BACKUP_DIR/$BACKUP_FILE
+mkdir -p $LOGGING_DIR
+touch $LOGGING_DIR/$LOGGING_FILE
 
+# Is the backup host up?
 ping $BACKUP_ADDRESS -c2 
-if [ $? -eq0 ]; 
+
+if [ $? -eq 0 ]; 
 then 
   echo $BACKUP_ADDRESS online. Proceeding.
 else 
@@ -20,37 +23,39 @@ else
   exit 1 
 fi 
 
-echo "[$(date --iso-8601=seconds)] Started backup run" >> $BACKUP_DIR/$BACKUP_FILE
+echo "[$(date --iso-8601=seconds)] Started backup run" >> $LOGGING_DIR/$LOGGING_FILE
 
 # /usr/bin/curl -s --form-string token="{{vault_pushover_home_automation_key}}" --form-string user="{{vault_pushover_user_key}}" --form-string message="{{inventory_hostname}} backup started - $(date --iso-8601=seconds)" https://api.pushover.net/1/messages.json
 
 {% for item in backup_datasets %}
-echo "[$(date --iso-8601=seconds)] START {{item}} " >> $BACKUP_DIR/$BACKUP_FILE
+echo "[$(date --iso-8601=seconds)] START {{item}} " >> $LOGGING_DIR/$LOGGING_FILE
 SYNCOID_OUTPUT=$( /usr/sbin/syncoid --sendoptions=Rw --no-privilege-elevation --no-sync-snap --quiet zfsbackup@$BACKUP_ADDRESS:{{item}} backups/{{item}} 2>&1 )
 
 if [ $? -eq 0 ]
 then
-    echo "[$(date --iso-8601=seconds)] SUCCESS {{item}}" >> $BACKUP_DIR/$BACKUP_FILE
+    echo "[$(date --iso-8601=seconds)] SUCCESS {{item}}" >> $LOGGING_DIR/$LOGGING_FILE
+		echo "Successfully backed up {{item}}"
 else
     FAILURE=1
-    echo "[$(date --iso-8601=seconds)] FAILURE {{item}} " >> $BACKUP_DIR/$BACKUP_FILE
-    echo "[$(date --iso-8601=seconds)] FAILURE {{item}} " >> $BACKUP_DIR/$BACKUP_FILE_FAILURE
-    echo "[$(date --iso-8601=seconds)] FAILURE OUTPUT: " >> $BACKUP_DIR/$BACKUP_FILE_FAILURE
-    echo $SYNCOID_OUTPUT >> $BACKUP_DIR/$BACKUP_FILE_FAILURE
+    echo "[$(date --iso-8601=seconds)] FAILURE {{item}} " >> $LOGGING_DIR/$LOGGING_FILE
+    echo "[$(date --iso-8601=seconds)] FAILURE {{item}} " >> $LOGGING_DIR/$ERROR_FILE
+    echo "[$(date --iso-8601=seconds)] FAILURE OUTPUT: " >> $LOGGING_DIR/$ERROR_FILE
+    echo $SYNCOID_OUTPUT >> $LOGGING_DIR/$ERROR_FILE
+		echo $SYNCOID_OUTPUT
 fi
-echo "[$(date --iso-8601=seconds)] END {{item}} " >> $BACKUP_DIR/$BACKUP_FILE
+echo "[$(date --iso-8601=seconds)] END {{item}} " >> $LOGGING_DIR/$LOGGING_FILE
 {% endfor %}
 
-echo "[$(date --iso-8601=seconds)] Finished backup run" >> $BACKUP_DIR/$BACKUP_FILE
-echo " " >> $BACKUP_DIR/$BACKUP_FILE
-echo "---------------------" >> $BACKUP_DIR/$BACKUP_FILE
-echo " " >> $BACKUP_DIR/$BACKUP_FILE
+echo "[$(date --iso-8601=seconds)] Finished backup run" >> $LOGGING_DIR/$LOGGING_FILE
+echo " " >> $LOGGING_DIR/$LOGGING_FILE
+echo "---------------------" >> $LOGGING_DIR/$LOGGING_FILE
+echo " " >> $LOGGING_DIR/$LOGGING_FILE
 
 # Notify of outcome
 if [ $FAILURE -eq 1 ]
 then
-    echo "Backup failure"
-    /usr/bin/beep -f 5000 -l 50 -r 6
+    echo "Backup failure - logged to $LOGGING_DIR/$ERROR_FILE"
+    # /usr/bin/beep -f 5000 -l 50 -r 6
     /usr/bin/curl -s --form-string token="{{vault_pushover_home_automation_key}}" --form-string user="{{vault_pushover_user_key}}" --form-string message="Backup failed - $(date --iso-8601=seconds)" https://api.pushover.net/1/messages.json
 else
     echo "Backup success"
