skeleton nfs mount

diff --git a/ansible/roles/zfs-tools-backup-server/templates/backup.sh.j2 b/ansible/roles/zfs-tools-backup-server/templates/backup.sh.j2
--- a/ansible/roles/zfs-tools-backup-server/templates/backup.sh.j2
+++ b/ansible/roles/zfs-tools-backup-server/templates/backup.sh.j2
@@ -11,6 +11,15 @@ FAILURE=0
 mkdir -p $BACKUP_DIR
 touch $BACKUP_DIR/$BACKUP_FILE
 
+ping $BACKUP_ADDRESS -c2 
+if [ $? -eq0 ]; 
+then 
+  echo $BACKUP_ADDRESS online. Proceeding.
+else 
+  echo $BACKUP_ADDRESS offline. Failure.
+  exit 1 
+fi 
+
 echo "[$(date --iso-8601=seconds)] Started backup run" >> $BACKUP_DIR/$BACKUP_FILE
 
 # /usr/bin/curl -s --form-string token="{{vault_pushover_home_automation_key}}" --form-string user="{{vault_pushover_user_key}}" --form-string message="{{inventory_hostname}} backup started - $(date --iso-8601=seconds)" https://api.pushover.net/1/messages.json
@@ -40,9 +49,11 @@ echo " " >> $BACKUP_DIR/$BACKUP_FILE
 # Notify of failure
 if [ $FAILURE -eq 1 ]
 then
+    echo "Backup failure"
     /usr/bin/beep -f 5000 -l 50 -r 6
     /usr/bin/curl -s --form-string token="{{vault_pushover_home_automation_key}}" --form-string user="{{vault_pushover_user_key}}" --form-string message="Backup failed - $(date --iso-8601=seconds)" https://api.pushover.net/1/messages.json
 else
-    echo "No tears, just dreams"
+    echo "Backup failure"
+    echo "Going to sleep..."
     rtcwake -m no -l -t $(date --date "tomorrow 08:50" +%s)
 fi
